// cmd/pulsemetry-gui/frontend/src/pages/tray/components/RecentSessionRow.svelte
<script lang="ts">
  import { openMainWindow } from "$lib/ipc/app";
  import AgentBadge from "$lib/components/ui/AgentBadge.svelte";
  import Dot from "$lib/components/ui/Dot.svelte";
  import type { TraySession } from "../types";

  let { session }: { session: TraySession } = $props();

  let titleViewport: HTMLSpanElement;
  let titleText: HTMLSpanElement;
  let overflow = $state(0);

  function measureTitle() {
    overflow = Math.max(0, titleText.scrollWidth - titleViewport.clientWidth);
  }
</script>

<button
  type="button"
  onclick={openMainWindow}
  onmouseenter={measureTitle}
  onfocus={measureTitle}
  class="session-row bg-surface hover:bg-surface-hover grid w-full cursor-pointer items-center text-left"
  style="grid-template-columns:8px 24px minmax(0,1fr);gap:9px;border:1px solid var(--color-border);border-left:3px solid {session.live
    ? 'var(--color-sand)'
    : 'var(--color-border)'};border-radius:11px;padding:7px 11px;margin-bottom:7px"
>
  <Dot
    color={session.live
      ? "var(--color-sand)"
      : "var(--color-border-strong)"}
    pulse={session.live}
  />
  <AgentBadge agent={session.agentId} size={24} />
  <span style="min-width:0">
    <span
      bind:this={titleViewport}
      class="session-title text-text block overflow-hidden whitespace-nowrap font-semibold"
      class:overflowing={overflow > 0}
      style="font-size:12.5px;margin-bottom:2px;--title-offset:-{overflow}px;--title-duration:{overflow / 35}s"
      ><span bind:this={titleText} class="title-text block truncate">{session.title}</span></span
    >
    <span class="text-text-muted block truncate" style="font-size:10.5px">
      {session.sub}
    </span>
  </span>
</button>

<style>
  @media (prefers-reduced-motion: no-preference) {
    .session-row:is(:hover, :focus-visible) .overflowing .title-text {
      overflow: visible;
      text-overflow: clip;
      transform: translateX(var(--title-offset));
      transition: transform var(--title-duration) linear 0.4s;
    }
  }
</style>

// cmd/pulsemetry-gui/frontend/src/pages/tray/components/RecentSessionRow.tsx
import AgentBadge from "$lib/components/ui/AgentBadge";
import Dot from "$lib/components/ui/Dot";
import { openMainWindow } from "$lib/ipc/app";
import { cssStyle } from "$lib/react-utils";
import { useState } from "react";
import type { TraySession } from "../types";
import "./RecentSessionRow.css";

export default function RecentSessionRow({
  session,
}: {
  session: TraySession;
}) {
  const [titleViewport, setTitleViewport] = useState<HTMLSpanElement | null>(
    null,
  );
  const [titleText, setTitleText] = useState<HTMLSpanElement | null>(null);
  const [overflow, setOverflow] = useState(0);

  function measureTitle() {
    if (!titleText || !titleViewport) return;
    setOverflow(Math.max(0, titleText.scrollWidth - titleViewport.clientWidth));
  }

  return (
    <>
      <button
        type="button"
        onClick={openMainWindow}
        onMouseEnter={measureTitle}
        onFocus={measureTitle}
        style={cssStyle(
          "border-left:3px solid " +
            String(session.live ? "var(--color-sand)" : "var(--color-border)"),
        )}
        className="session-row bg-surface hover:bg-surface-hover grid w-full cursor-pointer items-center text-left scope-x6o5n4 grid-cols-[8px_24px_minmax(0,1fr)] gap-[9px] [border:1px_solid_var(--color-border)] rounded-[11px] p-[7px_11px] mb-[7px]"
      >
        <Dot
          color={
            session.live ? "var(--color-sand)" : "var(--color-border-strong)"
          }
          pulse={session.live}
        />
        <AgentBadge agent={session.agentId} size={24} />
        <span className="scope-x6o5n4 min-w-0">
          <span
            ref={setTitleViewport}
            style={cssStyle(
              "--title-offset:-" +
                String(overflow) +
                "px;--title-duration:" +
                String(overflow / 35) +
                "s",
            )}
            className={[
              [
                "session-title text-text block overflow-hidden whitespace-nowrap font-semibold",
                overflow > 0 ? "overflowing" : "",
                "scope-x6o5n4",
              ]
                .filter(Boolean)
                .join(" "),
              "text-[12.5px] mb-[2px]",
            ]
              .filter(Boolean)
              .join(" ")}
          >
            <span
              ref={setTitleText}
              className="title-text block truncate scope-x6o5n4"
            >
              {session.title}
            </span>
          </span>
          <span className="text-text-muted block truncate scope-x6o5n4 text-[10.5px]">
            {session.sub}
          </span>
        </span>
      </button>
    </>
  );
}
