// cmd/pulsemetry-gui/frontend/src/pages/activity/components/SessionDetail.tsx
import AgentBadge from "$lib/components/ui/AgentBadge";
import Pill from "$lib/components/ui/Pill";
import ChevronLeftIcon from "$lib/icons/ChevronLeftIcon";
import ChevronRightIcon from "$lib/icons/ChevronRightIcon";
import XIcon from "$lib/icons/XIcon";
import { cssStyle, Portal, usePresence } from "$lib/react-utils";
import { Fragment, useEffect, useState } from "react";
import { detailDisplay } from "../model";
import type { ActivitySession } from "../types";
import FileChanges from "./FileChanges";
import KpiGrid from "./KpiGrid";
import TurnCard from "./TurnCard";
import TurnFlow from "./TurnFlow";

export default function SessionDetail({
  open = false,
  session,
  position,
  onClose,
  onPrev,
  onNext,
  loading = false,
  error = "",
  onRetry,
}: {
  loading?: boolean;
  error?: string;
  onRetry?: () => void;
  open?: boolean;
  session: ActivitySession | null;
  position: string;
  onClose?: () => void;
  onPrev?: () => void;
  onNext?: () => void;
}) {
  const present = usePresence(open, 280);
  const [turnOpen, setTurnOpen] = useState<Record<number, boolean>>({});
  const [turnSel, setTurnSel] = useState<number | null>(null);
  const [filesOpen, setFilesOpen] = useState(false);
  const [last, setLast] = useState<ActivitySession | null>(null);
  const [lastPosition, setLastPosition] = useState("");

  useEffect(() => {
    if (!session) return;
    const changed = last?.id !== session.id;

    setLast(session);
    setLastPosition(position);
    // 세션이 바뀌면 턴 펼침·선택·파일 목록 상태를 초기화한다.
    if (changed) {
      setTurnOpen({});
      setTurnSel(null);
      setFilesOpen(false);
    }
  }, [session, position, last?.id]);

  const shown = session ?? last;
  const d = shown ? detailDisplay(shown, position || lastPosition) : null;
  const openCount = Object.values(turnOpen).filter(Boolean).length;
  const collapseLabel = openCount ? "모두 접기" : "모두 펼치기";

  function toggleTurn(k: number) {
    const next = !turnOpen[k];

    setTurnOpen({ ...turnOpen, [k]: next });
    if (next) setTurnSel(k);
  }

  function pickTurn(k: number) {
    setTurnSel(k);
    setTurnOpen({ ...turnOpen, [k]: true });
  }

  function collapseAll() {
    if (openCount) {
      setTurnOpen({});

      return;
    }
    const all: Record<number, boolean> = {};

    d?.turns.forEach((t) => (all[t.n] = true));
    setTurnOpen(all);
  }

  return (
    <>
      {present && d ? (
        <>
          <Portal>
            <div
              data-open={open}
              className="session-overlay fixed inset-0 z-[60]"
            >
              <button
                type="button"
                aria-label="닫기"
                onClick={() => onClose?.()}
                className="absolute inset-0 cursor-default border-none [background:rgba(27,26,24,0.28)]"
              />
              <div className="session-sheet bg-surface absolute top-0 right-0 bottom-0 flex flex-col w-[min(720px,70vw)] [border-left:1px_solid_var(--color-border)] [box-shadow:-18px_0_44px_rgba(27,26,24,0.13)]">
                <div className="flex-none p-[20px_24px_16px] [border-bottom:1px_solid_#f1ece4]">
                  <div className="flex items-start gap-[14px] mb-[14px]">
                    <AgentBadge agent={d.agentId} size={40} />
                    <div className="min-w-0 flex-1">
                      <div className="text-text overflow-hidden font-bold text-ellipsis whitespace-nowrap text-[21px] tracking-[-0.02em] mb-[7px]">
                        {d.title}
                      </div>
                      <div className="flex items-baseline [font-family:var(--font-mono)] text-[12.5px] mb-[8px]">
                        <span className="text-text flex-none">{d.repo}</span>
                        <span className="text-text-muted flex-none p-[0_5px]">
                          /
                        </span>
                        <span className="text-text-muted min-w-0 overflow-hidden text-ellipsis whitespace-nowrap [flex:0_1_auto] [direction:rtl] [text-align:left]">
                          <bdi>{d.path}</bdi>
                        </span>
                      </div>
                      <div className="text-text-muted flex items-center whitespace-nowrap gap-[9px] text-[12.5px]">
                        <span className="text-text-secondary flex-none font-medium">
                          {d.agentName}
                        </span>
                        <Pill
                          label={d.badge.label}
                          fg={d.badge.fg}
                          bg={d.badge.bg}
                          fontSize={11.5}
                          padding="4px 8px"
                          className="flex-none"
                        />
                        <span
                          style={cssStyle(
                            "color:" +
                              String(d.character.fg) +
                              ";background:" +
                              String(d.character.bg) +
                              ";border-color:" +
                              String(d.character.border),
                          )}
                          className="inline-flex flex-none items-center border font-semibold gap-[6px] text-[11.5px] rounded-[7px] p-[4px_9px]"
                        >
                          <span
                            style={cssStyle(
                              "background:" + String(d.character.dot),
                            )}
                            className="flex-none w-[7px] h-[7px] rounded-[2px]"
                          />
                          {d.character.label}
                        </span>
                        <span className="overflow-hidden text-ellipsis">
                          {d.range}
                        </span>
                      </div>
                    </div>
                    <button
                      type="button"
                      aria-label="닫기"
                      onClick={() => onClose?.()}
                      className="border-border text-text-secondary hover:border-border-strong flex flex-none cursor-pointer items-center justify-center border bg-transparent w-[30px] h-[30px] rounded-[9px]"
                    >
                      <XIcon />
                    </button>
                  </div>
                </div>
                <div className="flex min-h-0 flex-1 flex-col overflow-y-auto p-[18px_24px_22px] gap-[14px]">
                  {loading ? (
                    <>
                      <p role="status">세션 상세를 불러오는 중입니다.</p>
                    </>
                  ) : (
                    <>
                      {error && d.kpi.length === 0 ? (
                        <>
                          <div role="alert">
                            {error}
                            <button onClick={() => onRetry?.()}>
                              다시 시도
                            </button>
                          </div>
                        </>
                      ) : (
                        <>
                          {error ? (
                            <>
                              <p role="alert">
                                {error} 마지막 조회 결과를 표시합니다.{" "}
                                <button onClick={() => onRetry?.()}>
                                  다시 시도
                                </button>
                              </p>
                            </>
                          ) : null}
                          {shown?.notice ? (
                            <>
                              <p role="status">{shown.notice}</p>
                            </>
                          ) : null}
                          <KpiGrid kpi={d.kpi} />
                          <TurnFlow
                            turnCount={d.turnCount}
                            segments={d.segments}
                            legend={d.legend}
                            selected={turnSel}
                            onPick={pickTurn}
                          />
                          <div>
                            <div className="flex items-baseline gap-[9px] mb-[9px]">
                              <span className="text-text-secondary font-semibold text-[12.5px]">
                                턴별 프롬프트
                              </span>
                              <span className="flex-1" />
                              <button
                                type="button"
                                onClick={collapseAll}
                                className="text-text-secondary hover:text-text cursor-pointer border-none bg-transparent font-semibold whitespace-nowrap text-[11.5px]"
                              >
                                {collapseLabel}
                              </button>
                            </div>
                            {d.turns.map((turn) => (
                              <Fragment key={turn.n}>
                                <TurnCard
                                  turn={turn}
                                  open={!!turnOpen[turn.n]}
                                  sel={turnSel === turn.n}
                                  onToggle={() => toggleTurn(turn.n)}
                                />
                              </Fragment>
                            ))}
                          </div>
                          <FileChanges
                            files={d.files}
                            open={filesOpen}
                            onToggle={() => setFilesOpen(!filesOpen)}
                          />
                        </>
                      )}
                    </>
                  )}
                </div>
                <div className="bg-surface flex flex-none items-center gap-[10px] p-[14px_24px] [border-top:1px_solid_#f1ece4]">
                  <button
                    type="button"
                    onClick={() => onPrev?.()}
                    className="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap gap-[8px] text-[13px] p-[10px_15px] rounded-[9px]"
                  >
                    <ChevronLeftIcon
                      size={13}
                      strokeWidth={2.2}
                      className="text-text-secondary"
                    />{" "}
                    이전
                  </button>
                  <button
                    type="button"
                    onClick={() => onNext?.()}
                    className="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap gap-[8px] text-[13px] p-[10px_15px] rounded-[9px]"
                  >
                    다음{" "}
                    <ChevronRightIcon
                      size={13}
                      strokeWidth={2.2}
                      className="text-text-secondary"
                    />
                  </button>
                  <span className="text-text-muted text-[12.5px] tabular-nums">
                    {d.position}
                  </span>
                  <span className="flex-1" />
                  <button
                    type="button"
                    onClick={collapseAll}
                    className="text-text-secondary hover:text-text cursor-pointer border-none bg-transparent font-semibold whitespace-nowrap text-[12px] mr-[4px]"
                  >
                    {collapseLabel}
                  </button>
                  <span className="text-text-muted flex items-center whitespace-nowrap gap-[7px] text-[11.5px]">
                    <span className="border-border border [font-family:var(--font-mono)] rounded-[5px] p-[3px_6px]">
                      J
                    </span>
                    <span className="border-border border [font-family:var(--font-mono)] rounded-[5px] p-[3px_6px]">
                      K
                    </span>{" "}
                    이동{" "}
                    <span className="border-border border [font-family:var(--font-mono)] rounded-[5px] p-[3px_6px] ml-[6px]">
                      Esc
                    </span>{" "}
                    닫기
                  </span>
                </div>
              </div>
            </div>
          </Portal>
        </>
      ) : null}
    </>
  );
}

// cmd/pulsemetry-gui/frontend/src/pages/activity/SessionDetail.svelte
<script lang="ts">
  import { fade, fly } from "svelte/transition";
  import { cubicOut } from "svelte/easing";
  import { detailDisplay } from "./data";
  import KpiGrid from "./KpiGrid.svelte";
  import StageFlow from "./StageFlow.svelte";
  import EventTimeline from "./EventTimeline.svelte";
  import FileChanges from "./FileChanges.svelte";

  let {
    open = false,
    index,
    onClose,
    onPrev,
    onNext,
  }: {
    open?: boolean;
    index: number | null;
    onClose?: () => void;
    onPrev?: () => void;
    onNext?: () => void;
  } = $props();

  let n = $state(0);
  $effect(() => {
    if (index !== null) n = index;
  });

  const d = $derived(detailDisplay(n));

  function onOverlayKeydown(e: KeyboardEvent) {
    if (e.key === "Enter") onClose?.();
  }
  function onCloseKeydown(e: KeyboardEvent) {
    if (e.key === "Enter" || e.key === " ") onClose?.();
  }
</script>

{#if open}
  <div
    class="fixed inset-0"
    style="z-index:60;background:rgba(27,26,24,0.32)"
    role="button"
    tabindex="-1"
    aria-label="닫기"
    onclick={() => onClose?.()}
    onkeydown={onOverlayKeydown}
    transition:fade={{ duration: 180 }}
  ></div>
  <div
    class="bg-surface fixed top-0 right-0 bottom-0 flex flex-col"
    style="z-index:61;width:620px;border-left:1px solid var(--color-border);border-radius:16px 0 0 16px;box-shadow:-28px 0 60px rgba(27,26,24,0.14)"
    transition:fly={{ x: 620, duration: 240, opacity: 1, easing: cubicOut }}
  >
    <div class="flex-none" style="padding:22px 24px 16px;border-bottom:1px solid #f1ece4">
      <div class="flex items-start" style="gap:13px">
        <div
          class="flex flex-none items-center justify-center"
          style="width:44px;height:44px;border-radius:13px;background:{d.agentTile
            .bg};color:{d.agentTile.fg};font-size:{d.agentTile
            .size}px;font-weight:{d.agentTile.weight}"
        >
          {d.agentTile.glyph}
        </div>
        <div class="min-w-0 flex-1">
          <div
            class="text-text overflow-hidden font-bold text-ellipsis whitespace-nowrap"
            style="font-size:21px;letter-spacing:-0.02em;margin-bottom:6px"
          >
            {d.title}
          </div>
          <div
            class="flex items-baseline"
            style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;margin-bottom:8px"
          >
            <span class="text-text flex-none">{d.repo}</span>
            <span class="text-text-muted flex-none">&nbsp;/&nbsp;</span>
            <span
              class="text-text-muted min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap"
              style="direction:rtl;text-align:left"><bdi>{d.path}</bdi></span
            >
          </div>
          <div
            class="text-text-muted flex items-center overflow-hidden whitespace-nowrap"
            style="gap:9px;font-size:12px"
          >
            <span class="text-text-secondary flex-none" style="font-weight:500"
              >{d.agentName}</span
            >
            <span
              class="flex-none font-semibold"
              style="font-size:11px;border-radius:6px;padding:3px 7px;background:{d
                .badge.bg};color:{d.badge.fg}">{d.badge.label}</span
            >
            <span class="overflow-hidden text-ellipsis">{d.range}</span>
          </div>
        </div>
        <div
          class="border-border text-text-secondary hover:bg-surface-hover flex flex-none cursor-pointer items-center justify-center border"
          style="width:30px;height:30px;border-radius:9px"
          role="button"
          tabindex="0"
          aria-label="닫기"
          onclick={() => onClose?.()}
          onkeydown={onCloseKeydown}
        >
          <svg
            viewBox="0 0 24 24"
            style="width:15px;height:15px"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"><path d="m7 7 10 10M17 7 7 17"></path></svg
          >
        </div>
      </div>
      <div class="flex" style="gap:8px;margin-top:16px">
        <button
          type="button"
          class="hover:bg-accent-hover flex cursor-pointer items-center border-none font-semibold whitespace-nowrap text-white"
          style="gap:7px;background:var(--color-accent);font-size:12.5px;padding:9px 14px;border-radius:9px"
        >
          <svg
            viewBox="0 0 24 24"
            style="width:13px;height:13px"
            fill="none"
            stroke="#fffdfc"
            stroke-width="1.8"
            stroke-linejoin="round"><path d="M8 5.5 18 12 8 18.5z"></path></svg
          > 계속하기</button
        >
        <button
          type="button"
          class="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap"
          style="gap:8px;font-size:12.5px;padding:9px 14px;border-radius:9px"
        >
          다른 에이전트로 넘기기
          <svg
            viewBox="0 0 24 24"
            style="width:13px;height:13px"
            fill="none"
            stroke="var(--color-text-muted)"
            stroke-width="2.2"
            stroke-linecap="round"
            stroke-linejoin="round"><path d="m6 9 6 6 6-6"></path></svg
          ></button
        >
        <button
          type="button"
          class="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap"
          style="gap:7px;font-size:12.5px;padding:9px 14px;border-radius:9px"
        >
          <svg
            viewBox="0 0 24 24"
            style="width:13px;height:13px"
            fill="none"
            stroke="var(--color-text-secondary)"
            stroke-width="1.9"
            stroke-linejoin="round"><path d="M4 6h6l2 2.5h8V19H4z"></path></svg
          > 폴더 열기</button
        >
        <div class="flex-1"></div>
        <div
          class="border-border text-text-muted hover:bg-surface-hover flex flex-none cursor-pointer items-center justify-center border"
          style="width:30px;height:30px;border-radius:9px;font-size:14px"
        >
          •••
        </div>
      </div>
    </div>
    <div
      class="flex min-h-0 flex-1 flex-col overflow-y-auto"
      style="padding:18px 24px 22px;gap:14px"
    >
      <div class="text-text" style="font-size:13.5px;line-height:1.75">
        {d.summary}
      </div>
      <KpiGrid kpi={d.kpi} />
      <StageFlow stages={d.stages} />
      <div
        class="grid items-start"
        style="grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px"
      >
        <EventTimeline events={d.events} />
        <FileChanges files={d.files} />
      </div>
    </div>
    <div
      class="flex flex-none items-center"
      style="gap:10px;padding:12px 24px;border-top:1px solid #f1ece4;background:#faf7f2;border-radius:0 0 0 16px"
    >
      <button
        type="button"
        class="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap"
        style="gap:7px;font-size:12.5px;padding:8px 13px;border-radius:9px"
        onclick={() => onPrev?.()}
      >
        <svg
          viewBox="0 0 24 24"
          style="width:13px;height:13px"
          fill="none"
          stroke="var(--color-text-secondary)"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"><path d="m15 5-7 7 7 7"></path></svg
        > 이전</button
      >
      <button
        type="button"
        class="bg-surface border-border text-text hover:border-border-strong flex cursor-pointer items-center border font-semibold whitespace-nowrap"
        style="gap:7px;font-size:12.5px;padding:8px 13px;border-radius:9px"
        onclick={() => onNext?.()}
      >
        다음
        <svg
          viewBox="0 0 24 24"
          style="width:13px;height:13px"
          fill="none"
          stroke="var(--color-text-secondary)"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"><path d="m9 5 7 7-7 7"></path></svg
        ></button
      >
      <span class="text-text-muted" style="font-size:12px">{d.position}</span>
      <span class="flex-1"></span>
      <span
        class="text-text-muted flex items-center whitespace-nowrap"
        style="gap:6px;font-size:11.5px"
      >
        <span
          class="bg-surface border-border border"
          style="font-family:ui-monospace,Menlo,monospace;border-radius:5px;padding:2px 6px"
          >J</span
        >
        <span
          class="bg-surface border-border border"
          style="font-family:ui-monospace,Menlo,monospace;border-radius:5px;padding:2px 6px"
          >K</span
        > 이동
        <span
          class="bg-surface border-border border"
          style="font-family:ui-monospace,Menlo,monospace;border-radius:5px;padding:2px 6px;margin-left:6px"
          >Esc</span
        > 닫기</span
      >
    </div>
  </div>
{/if}
