// cmd/pulsemetry-gui/frontend/src/pages/home/Home.svelte
<script lang="ts">
  import { period, periodRangeText } from "$lib/domain/period.svelte";
  import { buildActivity, heroData, vendorRows } from "./mock";
  import UsageHero from "./components/UsageHero.svelte";
  import VendorTable from "./components/VendorTable.svelte";
  import ActivityList from "./components/ActivityList.svelte";
  import type { AppSection } from "$lib/navigation";

  let {
    onNavigate,
  }: {
    onNavigate?: (tab: AppSection) => void;
  } = $props();

  // 기간 스코프 — period(전역 날짜 범위) 변경에 전부 반응한다
  const p = $derived(period.value);
  const hero = $derived(heroData(p.start, p.end));
  const vendors = $derived(vendorRows(hero));
  const activity = $derived(buildActivity(p.start, p.end));

  // 범위 표기는 Activity 와 같은 함수를 쓴다 — 화면마다 날짜 표기가 다르면
  // 같은 기간을 보고 있다는 걸 알아채기 어렵다.
  const rangeText = $derived(periodRangeText(p));
</script>

<main
  class="mx-auto w-full flex-1"
  style="max-width:var(--page-max-width);padding:14px 32px 6px"
>
  <div class="flex items-baseline" style="gap:12px;margin-bottom:14px">
    <h1
      class="text-text m-0 font-bold"
      style="font-size:38px;letter-spacing:-0.035em;line-height:1"
    >
      Home
    </h1>
    <div class="text-text-muted" style="font-size:14px">({rangeText})</div>
  </div>

  <UsageHero {hero} />
  <VendorTable {vendors} />
  <ActivityList {activity} onViewAll={() => onNavigate?.("activity")} />
</main>

// cmd/pulsemetry-gui/frontend/src/pages/home/Home.tsx
import { period, periodRangeText, usePeriod } from "$lib/domain/period";
import type { AppSection } from "$lib/navigation";
import ActivityList from "./components/ActivityList";
import UsageHero from "./components/UsageHero";
import VendorTable from "./components/VendorTable";
import { buildActivity, heroData, vendorRows } from "./mock";

export default function Home({
  onNavigate,
}: {
  onNavigate?: (tab: AppSection) => void;
}) {
  usePeriod();
  const p = period.value;
  const hero = heroData(p.start, p.end);
  const vendors = vendorRows(hero);
  const activity = buildActivity(p.start, p.end);
  const rangeText = periodRangeText(p);

  return (
    <>
      <main className="mx-auto w-full flex-1 max-w-[var(--page-max-width)] p-[14px_32px_6px]">
        <div className="flex items-baseline gap-[12px] mb-[14px]">
          <h1 className="text-text m-0 font-bold text-[38px] tracking-[-0.035em] leading-none">
            Home
          </h1>
          <div className="text-text-muted text-[14px]">({rangeText})</div>
        </div>
        <UsageHero hero={hero} />
        <VendorTable vendors={vendors} />
        <ActivityList
          activity={activity}
          onViewAll={() => onNavigate?.("activity")}
        />
      </main>
    </>
  );
}
