// cmd/pulsemetry-gui/frontend/src/pages/activity/components/TurnCard.tsx
import ChevronDownIcon from "$lib/icons/ChevronDownIcon";
import { cssStyle } from "$lib/react-utils";
import { Fragment } from "react";
import type { TurnDisplay } from "../types";

export default function TurnCard({
  turn,
  open,
  sel,
  onToggle,
}: {
  turn: TurnDisplay;
  open: boolean;
  sel: boolean;
  onToggle?: () => void;
}) {
  function copyPrompt() {
    navigator.clipboard?.writeText(turn.prompt);
  }

  return (
    <>
      <div
        style={cssStyle(
          "border-color:" +
            String(sel ? "var(--color-border-strong)" : "#efe9e1") +
            ";background:" +
            String(sel ? "var(--color-surface-hover)" : "var(--color-surface)"),
        )}
        className="border rounded-[12px] p-[12px_14px] mb-[8px]"
      >
        <button
          type="button"
          aria-expanded={open}
          onClick={() => onToggle?.()}
          className="grid w-full cursor-pointer items-center text-left grid-cols-[26px_44px_60px_minmax(0,1fr)_auto_14px] gap-[11px]"
        >
          <span
            style={cssStyle(
              "background:" +
                String(sel ? turn.labelDot : "#f4f0e9") +
                ";color:" +
                String(
                  sel ? "var(--color-surface)" : "var(--color-accent-hover)",
                ),
            )}
            className="flex items-center justify-center font-bold w-[26px] h-[26px] rounded-[8px] text-[11.5px] tabular-nums"
          >
            {turn.n}
          </span>
          <span className="text-text-secondary whitespace-nowrap text-[12px] tabular-nums">
            {turn.time}
          </span>
          <span
            style={cssStyle(
              "color:" +
                String(turn.labelFg) +
                ";background:" +
                String(turn.labelBg) +
                ";border-color:" +
                String(turn.labelBorder),
            )}
            className="inline-flex items-center justify-center border font-semibold whitespace-nowrap gap-[5px] text-[11px] rounded-[6px] p-[4px_0]"
          >
            <span
              style={cssStyle("background:" + String(turn.labelDot))}
              className="flex-none w-[6px] h-[6px] rounded-[2px]"
            />
            {turn.label}
          </span>
          <span className="text-text min-w-0 overflow-hidden text-ellipsis whitespace-nowrap text-[13px]">
            {turn.preview}
          </span>
          <span className="text-text-muted flex-none whitespace-nowrap text-[11px] tabular-nums">
            {turn.meta}
          </span>
          <ChevronDownIcon
            size={12}
            strokeWidth={2.4}
            rotated={open}
            className="text-text-muted flex-none"
          />
        </button>
        {open ? (
          <>
            <div className="animate-[rowIn_180ms_ease-out]">
              <div
                style={cssStyle(
                  "border-left:3px solid " + String(turn.labelFg),
                )}
                className="bg-surface mt-[12px] p-[11px_13px] [border:1px_solid_#efe9e1] rounded-[10px]"
              >
                <div className="flex items-baseline gap-[8px] mb-[7px]">
                  <span className="text-text-muted font-semibold text-[10.5px] tracking-[0.02em]">
                    보낸 프롬프트 원문
                  </span>
                  <span className="flex-1" />
                  <span className="text-text-muted whitespace-nowrap text-[10.5px]">
                    {turn.chars}
                  </span>
                  <button
                    type="button"
                    onClick={copyPrompt}
                    className="cursor-pointer border-none bg-transparent font-semibold whitespace-nowrap text-[10.5px] text-[var(--color-accent)]"
                  >
                    복사
                  </button>
                </div>
                <div className="text-text text-[13px] leading-[1.75] [white-space:pre-wrap] [word-break:break-word]">
                  {turn.prompt}
                </div>
              </div>
              <div className="grid grid-cols-[repeat(4,minmax(0,1fr))] gap-[8px] mt-[10px]">
                {turn.stats.map((stat) => (
                  <Fragment key={stat.name}>
                    <div className="bg-surface-hover [border:1px_solid_#efe9e1] rounded-[10px] p-[9px_11px]">
                      <div
                        style={cssStyle("color:" + String(stat.fg))}
                        className="text-[14px] font-bold tabular-nums mb-[3px]"
                      >
                        {stat.value}
                      </div>
                      <div className="text-text-muted whitespace-nowrap text-[10.5px]">
                        {stat.name}
                      </div>
                    </div>
                  </Fragment>
                ))}
              </div>
              <div className="bg-surface-hover mt-[10px] [border:1px_solid_#efe9e1] rounded-[10px] p-[11px_13px]">
                <div className="flex items-baseline gap-[8px] mb-[9px]">
                  <span className="text-text-muted font-semibold text-[10.5px] tracking-[0.02em]">
                    도구 호출
                  </span>
                  <span className="flex-1" />
                  <span className="text-text-muted whitespace-nowrap text-[10.5px]">
                    {turn.callNote}
                  </span>
                </div>
                {turn.calls.map((call, i) => (
                  <Fragment key={call.id ?? i}>
                    <div className="grid items-center grid-cols-[42px_62px_minmax(0,1fr)_46px_14px] gap-[10px] p-[5px_0]">
                      <span className="text-text-muted whitespace-nowrap text-[11px] tabular-nums">
                        {call.time}
                      </span>
                      <span className="text-text-secondary overflow-hidden font-semibold text-ellipsis whitespace-nowrap text-[11px]">
                        {call.tool}
                      </span>
                      <span className="text-text min-w-0 overflow-hidden text-ellipsis whitespace-nowrap [font-family:var(--font-mono)] text-[11px]">
                        {call.arg}
                      </span>
                      <span className="text-text-muted whitespace-nowrap text-[11px] tabular-nums [text-align:right]">
                        {call.dur}
                      </span>
                      <span
                        style={cssStyle(
                          "background:" +
                            String(
                              call.ok === null
                                ? "var(--color-surface-hover)"
                                : call.ok
                                  ? "var(--color-success-soft)"
                                  : "var(--color-danger-soft)",
                            ) +
                            ";color:" +
                            String(
                              call.ok === null
                                ? "var(--color-text-muted)"
                                : call.ok
                                  ? "#2f7e55"
                                  : "var(--color-danger-strong)",
                            ),
                        )}
                        className="flex items-center justify-center font-bold w-[14px] h-[14px] rounded-[4px] text-[9px]"
                      >
                        {call.ok === null ? "?" : call.ok ? "✓" : "✕"}
                      </span>
                    </div>
                  </Fragment>
                ))}
                <div className="text-text-muted text-[10.5px] mt-[8px] pt-[8px] [border-top:1px_solid_#f1ece4] leading-[1.6]">
                  수집된 도구 이름·대상·소요 시간·성공 여부를 표시합니다.
                </div>
              </div>
            </div>
          </>
        ) : null}
      </div>
    </>
  );
}

// cmd/pulsemetry-gui/frontend/src/pages/activity/components/TurnCard.svelte
<script lang="ts">
  import type { TurnDisplay } from "../types";
  import ChevronDownIcon from "$lib/icons/ChevronDownIcon.svelte";

  let {
    turn,
    open,
    sel,
    onToggle,
  }: {
    turn: TurnDisplay;
    open: boolean;
    sel: boolean;
    onToggle?: () => void;
  } = $props();

  function copyPrompt() {
    navigator.clipboard?.writeText(turn.prompt);
  }
</script>

<div
  class="border"
  style="border-color:{sel
    ? 'var(--color-border-strong)'
    : '#efe9e1'};border-radius:12px;background:{sel
    ? 'var(--color-surface-hover)'
    : 'var(--color-surface)'};padding:12px 14px;margin-bottom:8px"
>
  <button
    type="button"
    class="grid w-full cursor-pointer items-center text-left"
    style="grid-template-columns:26px 44px 60px minmax(0,1fr) auto 14px;gap:11px"
    aria-expanded={open}
    onclick={() => onToggle?.()}
  >
    <span
      class="flex items-center justify-center font-bold"
      style="width:26px;height:26px;border-radius:8px;background:{sel
        ? turn.labelDot
        : '#f4f0e9'};color:{sel
        ? 'var(--color-surface)'
        : 'var(--color-accent-hover)'};font-size:11.5px;font-variant-numeric:tabular-nums"
      >{turn.n}</span
    >
    <span
      class="text-text-secondary whitespace-nowrap"
      style="font-size:12px;font-variant-numeric:tabular-nums">{turn.time}</span
    >
    <span
      class="inline-flex items-center justify-center border font-semibold whitespace-nowrap"
      style="gap:5px;font-size:11px;border-radius:6px;padding:4px 0;color:{turn.labelFg};background:{turn.labelBg};border-color:{turn.labelBorder}"
    >
      <span
        class="flex-none"
        style="width:6px;height:6px;border-radius:2px;background:{turn.labelDot}"
      ></span>{turn.label}
    </span>
    <span
      class="text-text min-w-0 overflow-hidden text-ellipsis whitespace-nowrap"
      style="font-size:13px">{turn.preview}</span
    >
    <span
      class="text-text-muted flex-none whitespace-nowrap"
      style="font-size:11px;font-variant-numeric:tabular-nums">{turn.meta}</span
    >
    <ChevronDownIcon
      size={12}
      strokeWidth={2.4}
      class="text-text-muted flex-none"
      rotated={open}
    />
  </button>

  {#if open}
    <div style="animation:rowIn 180ms ease-out">
      <div
        class="bg-surface"
        style="margin-top:12px;padding:11px 13px;border:1px solid #efe9e1;border-left:3px solid {turn.labelFg};border-radius:10px"
      >
        <div class="flex items-baseline" style="gap:8px;margin-bottom:7px">
          <span
            class="text-text-muted font-semibold"
            style="font-size:10.5px;letter-spacing:0.02em"
            >보낸 프롬프트 원문</span
          >
          <span class="flex-1"></span>
          <span
            class="text-text-muted whitespace-nowrap"
            style="font-size:10.5px">{turn.chars}</span
          >
          <button
            type="button"
            class="cursor-pointer border-none bg-transparent font-semibold whitespace-nowrap"
            style="font-size:10.5px;color:var(--color-accent)"
            onclick={copyPrompt}>복사</button
          >
        </div>
        <div
          class="text-text"
          style="font-size:13px;line-height:1.75;white-space:pre-wrap;word-break:break-word"
        >
          {turn.prompt}
        </div>
      </div>

      <div
        class="grid"
        style="grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:10px"
      >
        {#each turn.stats as stat (stat.name)}
          <div
            class="bg-surface-hover"
            style="border:1px solid #efe9e1;border-radius:10px;padding:9px 11px"
          >
            <div
              style="font-size:14px;font-weight:700;font-variant-numeric:tabular-nums;margin-bottom:3px;color:{stat.fg}"
            >
              {stat.value}
            </div>
            <div
              class="text-text-muted whitespace-nowrap"
              style="font-size:10.5px"
            >
              {stat.name}
            </div>
          </div>
        {/each}
      </div>

      <div
        class="bg-surface-hover"
        style="margin-top:10px;border:1px solid #efe9e1;border-radius:10px;padding:11px 13px"
      >
        <div class="flex items-baseline" style="gap:8px;margin-bottom:9px">
          <span
            class="text-text-muted font-semibold"
            style="font-size:10.5px;letter-spacing:0.02em">도구 호출</span
          >
          <span class="flex-1"></span>
          <span
            class="text-text-muted whitespace-nowrap"
            style="font-size:10.5px">{turn.callNote}</span
          >
        </div>
        {#each turn.calls as call, i (call.id ?? i)}
          <div
            class="grid items-center"
            style="grid-template-columns:42px 62px minmax(0,1fr) 46px 14px;gap:10px;padding:5px 0"
          >
            <span
              class="text-text-muted whitespace-nowrap"
              style="font-size:11px;font-variant-numeric:tabular-nums"
              >{call.time}</span
            >
            <span
              class="text-text-secondary overflow-hidden font-semibold text-ellipsis whitespace-nowrap"
              style="font-size:11px">{call.tool}</span
            >
            <span
              class="text-text min-w-0 overflow-hidden text-ellipsis whitespace-nowrap"
              style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px"
              >{call.arg}</span
            >
            <span
              class="text-text-muted whitespace-nowrap"
              style="font-size:11px;font-variant-numeric:tabular-nums;text-align:right"
              >{call.dur}</span
            >
            <span
              class="flex items-center justify-center font-bold"
              style="width:14px;height:14px;border-radius:4px;font-size:9px;background:{call.ok === null ? 'var(--color-surface-hover)' : call.ok
                ? 'var(--color-success-soft)'
                : 'var(--color-danger-soft)'};color:{call.ok === null ? 'var(--color-text-muted)' : call.ok
                ? '#2f7e55'
                : 'var(--color-danger-strong)'}">{call.ok === null ? "?" : call.ok ? "✓" : "✕"}</span
            >
          </div>
        {/each}
        <div
          class="text-text-muted"
          style="font-size:10.5px;margin-top:8px;padding-top:8px;border-top:1px solid #f1ece4;line-height:1.6"
        >
          수집된 도구 이름·대상·소요 시간·성공 여부를 표시합니다.
        </div>
      </div>
    </div>
  {/if}
</div>
