// cmd/pulsemetry-gui/frontend/src/lib/components/Dot.svelte
<script lang="ts">
  // 상태 점. 지름과 색만 다를 뿐 같은 도형이 화면 곳곳에 반복된다.
  // pulse 는 "진행 중"을 나타내는 livePulse 링 애니메이션(app.css)을 켠다.
  let {
    size = 7,
    color,
    pulse = false,
    class: klass = "",
    style = "",
  }: {
    size?: number;
    color: string;
    pulse?: boolean;
    class?: string;
    style?: string;
  } = $props();
</script>

<span
  class="block flex-none {klass}"
  style="width:{size}px;height:{size}px;border-radius:50%;background:{color}{pulse
    ? ';animation:livePulse 2s ease-out infinite'
    : ''};{style}"
></span>

// cmd/pulsemetry-gui/frontend/src/lib/components/ui/Dot.tsx
import { cssStyle } from "$lib/react-utils";

export default function Dot({
  size = 7,
  color,
  pulse = false,
  className: klass = "",
  style = "",
}: {
  size?: number;
  color: string;
  pulse?: boolean;
  className?: string;
  style?: string;
}) {
  return (
    <>
      <span
        style={cssStyle(
          "width:" +
            String(size) +
            "px;height:" +
            String(size) +
            "px;border-radius:50%;background:" +
            String(color) +
            String(pulse ? ";animation:livePulse 2s ease-out infinite" : "") +
            ";" +
            String(style),
        )}
        className={"block flex-none " + String(klass)}
      />
    </>
  );
}
