// cmd/pulsemetry-gui/frontend/src/lib/components/ui/Select.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLSelectAttributes } from "svelte/elements";
  import ChevronDownIcon from "$lib/icons/ChevronDownIcon.svelte";

  // 디자인의 드롭다운은 버튼 모양이지만 실제로는 native select 를 쓴다. 값 바인딩·키보드
  // 조작·화면 낭독기를 그대로 얻으려면 select 여야 하고, 생김새만 appearance:none 으로
  // 벗겨 맞춘다. 화살표는 select 안에 넣을 수 없어 겹쳐 놓는다.
  //
  // 나머지 속성(aria-label 등)은 그대로 흘려보낸다 — 호출부가 쓰던 것을 여기서 다시
  // 정의하지 않는다.
  let {
    value = $bindable(""),
    children,
    class: klass = "",
    ...rest
  }: HTMLSelectAttributes & { value?: string; children?: Snippet } = $props();
</script>

<span class="relative inline-flex items-center {klass}">
  <select
    bind:value
    class="field bg-surface border-border text-text w-full cursor-pointer appearance-none border whitespace-nowrap"
    style="border-radius:10px;padding:10px 35px 10px 14px;font-size:13px;font-family:inherit"
    {...rest}
  >
    {@render children?.()}
  </select>
  <ChevronDownIcon
    size={13}
    strokeWidth={2.2}
    class="text-text-muted pointer-events-none absolute"
    style="right:14px"
  />
</span>

<style>
  .field:hover {
    border-color: var(--color-border-strong);
  }
</style>

// cmd/pulsemetry-gui/frontend/src/lib/components/ui/Select.tsx
import ChevronDownIcon from "$lib/icons/ChevronDownIcon";
import type { ReactNode as Snippet } from "react";
import "./Select.css";

export default function Select({
  value = "",
  children,
  className: klass = "",
  onValueChange,
  onChange,
  ...rest
}: React.SelectHTMLAttributes<HTMLSelectElement> & {
  value?: string;
  onValueChange?: (value: string) => void;
  children?: Snippet;
}) {
  return (
    <>
      <span
        className={[
          "relative inline-flex items-center " + String(klass),
          "scope-1o3rpsw",
        ]
          .filter(Boolean)
          .join(" ")}
      >
        <select
          value={value}
          onChange={(e) => {
            onValueChange?.(e.currentTarget.value);
            onChange?.(e);
          }}
          {...rest}
          className="field bg-surface border-border text-text w-full cursor-pointer appearance-none border whitespace-nowrap scope-1o3rpsw rounded-[10px] p-[10px_35px_10px_14px] text-[13px] [font-family:inherit]"
        >
          {children}
        </select>
        <ChevronDownIcon
          size={13}
          strokeWidth={2.2}
          className="text-text-muted pointer-events-none absolute [right:14px]"
        />
      </span>
    </>
  );
}
