// cmd/pulsemetry-gui/frontend/src/pages/home/components/ActivityList.tsx
import AgentBadge from "$lib/components/ui/AgentBadge";
import EmptyState from "$lib/components/ui/EmptyState";
import Pill from "$lib/components/ui/Pill";
import { cssStyle } from "$lib/react-utils";
import { Fragment } from "react";
import type { ActivityData } from "../types";

export default function ActivityList({
  activity,
  onViewAll,
}: {
  activity: ActivityData;
  onViewAll?: () => void;
}) {
  const STATUS = {
    running: { label: "진행 중", fg: "#8b6b36", bg: "var(--color-sand-soft)" },
    done: {
      label: "종료",
      fg: "var(--color-text-secondary)",
      bg: "var(--color-inactive-soft)",
    },
  } as const;
  const note = `${activity.total} 세션${activity.running ? ` · 진행 중 ${activity.running}` : ""}`;

  return (
    <>
      <div className="bg-surface border-border border rounded-[14px] p-[14px_22px_8px]">
        <div className="flex items-baseline gap-[10px] mb-[2px]">
          <div className="text-text font-bold text-[16px] tracking-[-0.01em]">
            활동
          </div>
          <div className="text-text-muted text-[12.5px]">{note}</div>
          <div className="flex-1" />
          <button
            type="button"
            onClick={onViewAll}
            className="text-text-secondary hover:text-text cursor-pointer border-none bg-transparent font-medium whitespace-nowrap text-[13px]"
          >
            전체 보기 →
          </button>
        </div>
        {activity.rows.length === 0 ? (
          <>
            <EmptyState
              title="표시할 세션이 없어요"
              description="선택한 기간에 실행된 세션이 없습니다."
            />
          </>
        ) : null}
        {activity.rows.map((t, i) => (
          <Fragment key={t.id}>
            {(() => {
              const st = STATUS[t.state];

              return (
                <>
                  <div
                    style={cssStyle(
                      "border-bottom:1px solid " +
                        String(
                          i === activity.rows.length - 1
                            ? "transparent"
                            : "#f5f1ea",
                        ),
                    )}
                    className="grid items-center grid-cols-[74px_28px_minmax(0,1fr)_46px_60px] gap-[12px] p-[9px_0]"
                  >
                    <span className="whitespace-nowrap tabular-nums">
                      <span className="text-text-muted block text-[11px] mb-[2px]">
                        {t.date}
                      </span>
                      <span className="text-text block font-semibold text-[12.5px]">
                        {t.time}
                      </span>
                    </span>
                    <AgentBadge agent={t.agent} size={28} />
                    <span className="min-w-0">
                      <span className="text-text block truncate font-semibold text-[13.5px] mb-[3px]">
                        {t.title}
                      </span>
                      <span className="text-text-muted block truncate text-[11px]">
                        {t.sub}
                      </span>
                    </span>
                    <span className="text-text-secondary text-right whitespace-nowrap text-[12.5px] tabular-nums">
                      {t.tokens}
                    </span>
                    <Pill
                      label={st.label}
                      fg={st.fg}
                      bg={st.bg}
                      className="justify-self-end"
                    />
                  </div>
                </>
              );
            })()}
          </Fragment>
        ))}
      </div>
    </>
  );
}

// cmd/pulsemetry-gui/frontend/src/pages/home/components/ActivityList.svelte
<script lang="ts">
  import AgentBadge from "$lib/components/ui/AgentBadge.svelte";
  import Pill from "$lib/components/ui/Pill.svelte";
  import EmptyState from "$lib/components/ui/EmptyState.svelte";
  import type { ActivityData } from "../types";

  let {
    activity,
    onViewAll,
  }: { activity: ActivityData; onViewAll?: () => void } = $props();

  // 종료는 성공/실패 판단 없이 "끝났다"는 사실만 담는다 — 초록은 성공으로 읽히고,
  // 작업 유형(검증) 배지가 이미 쓰고 있어 색이 겹친다. Activity 의 STATE_STYLE 과 같은 규칙.
  const STATUS = {
    running: { label: "진행 중", fg: "#8b6b36", bg: "var(--color-sand-soft)" },
    done: {
      label: "종료",
      fg: "var(--color-text-secondary)",
      bg: "var(--color-inactive-soft)",
    },
  } as const;

  const note = $derived(
    `${activity.total} 세션${activity.running ? ` · 진행 중 ${activity.running}` : ""}`,
  );
</script>

<div
  class="bg-surface border-border border"
  style="border-radius:14px;padding:14px 22px 8px"
>
  <div class="flex items-baseline" style="gap:10px;margin-bottom:2px">
    <div class="text-text font-bold" style="font-size:16px;letter-spacing:-0.01em">
      활동
    </div>
    <div class="text-text-muted" style="font-size:12.5px">{note}</div>
    <div style="flex:1"></div>
    <button
      type="button"
      onclick={onViewAll}
      class="text-text-secondary hover:text-text cursor-pointer border-none bg-transparent font-medium whitespace-nowrap"
      style="font-size:13px"
    >
      전체 보기 →
    </button>
  </div>

  {#if activity.rows.length === 0}
    <EmptyState
      title="표시할 세션이 없어요"
      description="선택한 기간에 실행된 세션이 없습니다."
    />
  {/if}
  {#each activity.rows as t, i (t.date + t.time + t.title)}
    {@const st = STATUS[t.state]}
    <div
      class="grid items-center"
      style="grid-template-columns:74px 28px minmax(0,1fr) 46px 60px;gap:12px;padding:9px 0;border-bottom:1px solid {i ===
      activity.rows.length - 1
        ? 'transparent'
        : '#f5f1ea'}"
    >
      <span class="whitespace-nowrap" style="font-variant-numeric:tabular-nums">
        <span class="text-text-muted block" style="font-size:11px;margin-bottom:2px">
          {t.date}
        </span>
        <span class="text-text block font-semibold" style="font-size:12.5px">
          {t.time}
        </span>
      </span>
      <AgentBadge agent={t.agent} size={28} />
      <span style="min-width:0">
        <span
          class="text-text block truncate font-semibold"
          style="font-size:13.5px;margin-bottom:3px"
        >
          {t.title}
        </span>
        <span class="text-text-muted block truncate" style="font-size:11px">
          {t.sub}
        </span>
      </span>
      <span
        class="text-text-secondary text-right whitespace-nowrap"
        style="font-size:12.5px;font-variant-numeric:tabular-nums"
      >
        {t.tokens}
      </span>
      <Pill
        class="justify-self-end"
        label={st.label}
        fg={st.fg}
        bg={st.bg}
      />
    </div>
  {/each}
</div>
