// cmd/pulsemetry-gui/frontend/src/pages/home/components/usage-chart/UsageChartTooltip.tsx
import { cssStyle } from "$lib/react-utils";
import { Fragment } from "react";
import type { HeroData } from "../../types";
import type { ChartBar } from "./layout";
import "./UsageChartTooltip.css";

export default function UsageChartTooltip({
  hero,
  bar,
  left,
  top,
}: {
  hero: HeroData;
  bar: ChartBar;
  left: number;
  top: number;
}) {
  return (
    <>
      <div
        style={cssStyle(
          "left:" + String(left) + "px;top:" + String(top) + "px",
        )}
        className="usage-tooltip pointer-events-none absolute z-10 bg-surface border-border border shadow-sm scope-1n5dj3j [transform:translate(-50%,-100%)] w-[184px] rounded-[9px] p-[9px_11px]"
      >
        <div className="text-text font-semibold scope-1n5dj3j text-[12px] mb-[7px]">
          {bar.label}
        </div>
        <div className="grid scope-1n5dj3j grid-cols-[1fr_auto] gap-[5px_10px] text-[11.5px]">
          {hero.legend.map((legend, index) => (
            <Fragment key={legend.name}>
              <span className="text-text-secondary flex items-center scope-1n5dj3j gap-[6px]">
                <span
                  style={cssStyle("background:" + String(legend.color))}
                  className="scope-1n5dj3j w-[7px] h-[7px] rounded-[2px]"
                />
                {legend.name}
              </span>
              <span className="font-semibold scope-1n5dj3j tabular-nums">
                {bar.values[index]}k
              </span>
            </Fragment>
          ))}
          <span className="text-text font-semibold scope-1n5dj3j pt-[3px] [border-top:1px_solid_#f1ece4]">
            합계
          </span>
          <span className="text-text text-right font-bold scope-1n5dj3j pt-[3px] [border-top:1px_solid_#f1ece4] tabular-nums">
            {bar.totalValue}k
          </span>
        </div>
      </div>
    </>
  );
}

// cmd/pulsemetry-gui/frontend/src/pages/home/components/usage-chart/UsageChartTooltip.svelte
<script lang="ts">
  import type { HeroData } from "../../types";
  import type { ChartBar } from "./layout";

  let {
    hero,
    bar,
    left,
    top,
  }: { hero: HeroData; bar: ChartBar; left: number; top: number } = $props();
</script>

<div
  class="usage-tooltip pointer-events-none absolute z-10 bg-surface border-border border shadow-sm"
  style="left:{left}px;top:{top}px;transform:translate(-50%,-100%);width:184px;border-radius:9px;padding:9px 11px"
>
  <div class="text-text font-semibold" style="font-size:12px;margin-bottom:7px">
    {bar.label}
  </div>
  <div
    class="grid"
    style="grid-template-columns:1fr auto;gap:5px 10px;font-size:11.5px"
  >
    {#each hero.legend as legend, index (legend.name)}
      <span class="text-text-secondary flex items-center" style="gap:6px">
        <span
          style="width:7px;height:7px;border-radius:2px;background:{legend.color}"
        ></span>
        {legend.name}
      </span>
      <span class="font-semibold" style="font-variant-numeric:tabular-nums">
        {bar.values[index]}k
      </span>
    {/each}
    <span
      class="text-text font-semibold"
      style="padding-top:3px;border-top:1px solid #f1ece4">합계</span
    >
    <span
      class="text-text text-right font-bold"
      style="padding-top:3px;border-top:1px solid #f1ece4;font-variant-numeric:tabular-nums"
    >
      {bar.totalValue}k
    </span>
  </div>
</div>

<style>
  .usage-tooltip {
    transition:
      left 400ms cubic-bezier(0.22, 1, 0.36, 1),
      top 400ms cubic-bezier(0.22, 1, 0.36, 1);
    animation: tooltip-in 200ms ease-out;
    will-change: left, top;
  }

  @keyframes tooltip-in {
    from {
      opacity: 0;
      margin-top: 3px;
    }
    to {
      opacity: 1;
      margin-top: 0;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .usage-tooltip {
      transition: none;
      animation: none;
    }
  }
</style>
